apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      environment: {{ .Values.app.environment }}
  template:
    metadata:
      labels:
        environment: {{ .Values.app.environment }}
    spec:
      containers:
        - name: conv-app
          image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
          ports: 
            - containerPort: {{ .Values.app.port}}
          resources:
            limits: {{ .Values.app.limits | toYaml | nintent 14 }}
          envFrom:
          - configMapRef:
              name: app-conv-configmap