apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  selector:
    matchLabels:
      part: converter
  template:
    metadata:
      labels:
        part: converter
    spec:
      containers:
      - name: converter
        image: antonlarichev/conv-service:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3333
