apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-conv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: api
  template:
    metadata:
      labels:
        environment: api
    spec:
      containers:
      - name: conv-api
        image: antonlarichev/conv-api:1.0
        ports:
        - containerPort: 3000
        env: 
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: api-secret
              key: DATABASE_URL
        - name: AMQP_EXCHANGE
          valueFrom: 
            secretKeyRef:
              name: api-secret
              key: AMQP_EXCHANGE
        - name: AMQP_USER
          valueFrom: 
            secretKeyRef:
              name: api-secret
              key: AMQP_USER
        - name: AMQP_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: api-secret
              key: AMQP_PASSWORD
        - name: AMQP_HOSTNAME
          valueFrom: 
            secretKeyRef:
              name: api-secret
              key: AMQP_HOSTNAME
        volumeMounts:
          - name: api-data
            mountPath: /opt/app/uploads
            readOnly: true
        livenessProbe:
          exec:
            command:
              - curl 
              - --fail
              - http://localhost:3000/api
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 2
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: api-data
        persistentVolumeClaim:  # ← Исправлено: строчные буквы
          claimName: api-pvc
