apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: rmq
  template:
    metadata:
      name: rmq
      labels:
        component: rmq
    spec:
      containers:
      - name: rmq
        image: rabbitmq:3.9
        ports:
        - containerPort: 5672   # 1. Документирует, что контейнер использует порт 5672
          name: amqp           # 2. Даёт имя для удобства
        - containerPort: 15672  # 3. Помогает инструментам (kubectl port-forward и др.)
          name: management
        env:
        - name: SEED_USERNAME
          valueFrom:
            secretKeyRef:
              name: rmq-secret
              key: SEED_USERNAME
        - name: SEED_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmq-secret
              key: SEED_USER_PASSWORD
        resources:
          requests: 
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
          subpath: rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim: 
          claimName: ramq-pvc

      