app:
  name: conv-app
  replicaCount: 1
  version: 1.2
  image: antonlarichev/conv-app
  environment: production
  port: 80
  limits:
    memory: "128Mi"
    cpu: "500m"
  data:  
    VITE_DOMAIN: http://conv.test/api
    AMQP_EXCHANGE: conv
    AMQP_USER: conv
    AMQP_PASSWORD: conv
    AMQP_HOSTNAME: conv
    AMQP_QUEUE: conv